# -*- coding: utf-8 -*-
"""MACHINE_LEARNING_AND_BIGDATA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PPDpjoxzkGSwhApgKhyZ6eaDOUeoDAFL
"""

import pandas as pd


#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.
data = pd.read_csv("tips.csv")

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.
display(data.head(10))

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.
! pip install matplotlib

import pandas as pd
import matplotlib.pyplot as plt


#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

data = pd.read_csv("tips.csv")

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

plt.scatter(data['Grade'], data['Division'])

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

plt.title("Scatter Plot")

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

plt.xlabel('Branch')
plt.ylabel('HeadcountMale')

plt.show()

import pandas as pd
import matplotlib.pyplot as plt


#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

data = pd.read_csv("tips.csv")

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

plt.plot(data['Branch'])
plt.plot(data['Grade'])

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

plt.title("Scatter Plot")

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.
plt.xlabel('Division')
plt.ylabel('HeadcountMale')

plt.show()

import pandas as pd
import matplotlib.pyplot as plt


#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

data = pd.read_csv("tips.csv")

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

plt.hist(data['Branch'])

plt.title("Histogram")

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

plt.show()

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.
! pip install seaborn

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd


#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

data = pd.read_csv("tips.csv")

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

sns.lineplot(x="Branch", y="Grade", data=data)

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

plt.title('Title using Matplotlib Function')

plt.show()

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

data = pd.read_csv("tips.csv")

sns.scatterplot(x='Branch', y='Grade', data=data,)
plt.show()

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

data = pd.read_csv("tips.csv")

sns.scatterplot(x='Branch', y='Grade', data=data,
			hue='Division')
plt.show()

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.
! pip install bokeh

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

from bokeh.plotting import figure, output_file, show
from bokeh.palettes import magma
import pandas as pd


#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

graph = figure(title = "Bokeh Scatter Graph")

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

data = pd.read_csv("tips.csv")

color = magma(256)

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

graph.scatter(data['HeadcountFemale'], data['Grade'], color=color)

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

show(graph)

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

from bokeh.plotting import figure, output_file, show
import pandas as pd


#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

graph = figure(title = "Bokeh Bar Chart")

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

data = pd.read_csv("tips.csv")

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.
#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

df = data['Grade'].value_counts()

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

graph.line(df, data['Grade'])

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

show(graph)

from bokeh.io import show
from bokeh.models import Button, CheckboxGroup, RadioGroup, CustomJS

button = Button(label="GFG")

button.js_on_click(CustomJS(
	code="console.log('button: click!', this.toString())"))

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

L = ["First", "Second", "Third"]

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

checkbox_group = CheckboxGroup(labels=L, active=[0, 2])

checkbox_group.js_on_click(CustomJS(code="""
	console.log('checkbox_group: active=' + this.active, this.toString())
"""))

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

radio_group = RadioGroup(labels=L, active=1)

radio_group.js_on_click(CustomJS(code="""
	console.log('radio_group: active=' + this.active, this.toString())
"""))

show(button)
show(checkbox_group)
show(radio_group)

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd


#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

data = pd.read_csv("tips.csv")

sns.lineplot(x='Branch', y='Grade', data=data)
plt.show()

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd


#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

data = pd.read_csv("tips.csv")

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

sns.lineplot(data=data.drop(['Branch'], axis=1))
plt.show()

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd


#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

data = pd.read_csv("tips.csv")

sns.barplot(x='HeadcountFemale',y='HeadcountMale', data=data,
			hue='Grade')

plt.show()

#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd


#The rising usage of digital technology and the internet of things (IoT), which create large volumes of data from many sources, is driving the emergence of big data. The four Vs of big data are volume, variety, velocity, and veracity. The volume of data is expanding exponentially, as is the variety of data kinds and sources. The rate at which data is created and processed is likewise increasing, and ensuring data quality and dependability is a significant concern. Big data analytics is a complicated process that entails gathering, storing, processing, analysing, and displaying massive amounts of data in order to extract important insights. Deep learning is a kind of AI that allows machines to gather information from data and enhance their abilities over a period without supervised learning. Image and audio recognition, processing of natural language, prescriptive modelling, and recommendation systems are among applications that employ machine learning techniques.

data = pd.read_csv("tips.csv")

sns.histplot(x='HeadcountMale', data=data, kde=True, hue='Grade')

plt.show()



